name: Test PR

on: [push]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: Kindergarten Menagement System

      - name: Build	
        run: dotnet build --no-restore
        working-directory: Kindergarten Menagement System

      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: Kindergarten Menagement System
